import 'package:flutter/material.dart';

class ShortcutIconCatalog {
  static const Map<String, IconData> _icons = {
    'language': Icons.language,
    'chat': Icons.chat,
    'camera_alt': Icons.camera_alt,
    'settings': Icons.settings,
    'apps': Icons.apps,
    'phone': Icons.phone,
    'message': Icons.message,
    'map': Icons.map,
    'shopping_cart': Icons.shopping_cart,
    'music_note': Icons.music_note,
    'video_call': Icons.video_call,
    'terminal': Icons.terminal,
    'play_arrow': Icons.play_arrow,
    'folder': Icons.folder,
    'email': Icons.email,
    'search': Icons.search,
    'home': Icons.home,
    'star': Icons.star,
    'send': Icons.send,
    'account_balance_wallet': Icons.account_balance_wallet,
    'qr_code': Icons.qr_code,
    'payments': Icons.payments,
    'photo': Icons.photo,
    'file_download': Icons.file_download,
    'notifications': Icons.notifications,
    'bookmark': Icons.bookmark,
    'share': Icons.share,
    'cloud': Icons.cloud,
    'power_settings_new': Icons.power_settings_new,
    'toggle_on': Icons.toggle_on,
    'location_on': Icons.location_on,
    'gps_fixed': Icons.gps_fixed,
    'navigation': Icons.navigation,
    'near_me': Icons.near_me,
    'wifi': Icons.wifi,
    'bluetooth': Icons.bluetooth,
    'flashlight_on': Icons.flashlight_on,
    'dark_mode': Icons.dark_mode,
    'arrow_back': Icons.arrow_back,
    'keyboard_return': Icons.keyboard_return,
    'swipe_up': Icons.swipe_up,
    'swipe_down': Icons.swipe_down,
    'mouse': Icons.mouse,
  };

  static const List<String> defaultKeys = [
    'language',
    'chat',
    'camera_alt',
    'settings',
    'apps',
    'phone',
    'message',
    'map',
    'shopping_cart',
    'music_note',
    'video_call',
    'terminal',
    'play_arrow',
    'folder',
    'email',
    'search',
    'home',
    'star',
    'send',
    'account_balance_wallet',
    'qr_code',
    'payments',
    'photo',
    'file_download',
    'notifications',
    'bookmark',
    'share',
    'cloud',
    'power_settings_new',
    'toggle_on',
    'location_on',
    'gps_fixed',
    'navigation',
    'near_me',
    'wifi',
    'bluetooth',
    'flashlight_on',
    'dark_mode',
    'arrow_back',
    'keyboard_return',
    'swipe_up',
    'swipe_down',
    'mouse',
  ];

  static IconData iconData(String key) => _icons[key] ?? Icons.apps;
}
